"""Generate native WPF drawings from the CC0 controller SVG, without rasterizing."""

from copy import deepcopy
from pathlib import Path
import re
import shutil
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SVG = ROOT / "docs/ux/controller-options/xbox-input-overlay.svg"
WPF = "http://schemas.microsoft.com/winfx/2006/xaml/presentation"
XAML = "http://schemas.microsoft.com/winfx/2006/xaml"
ET.register_namespace("", WPF)
ET.register_namespace("x", XAML)

PALETTE = {
    "#52645C": "Ink",
    "#FFFFFF": "Surface",
    "#E6ECE8": "Stick",
    "#8AB7A2": "Pressed",
}


def element(name, attributes=None, parent=None):
    result = ET.Element(f"{{{WPF}}}{name}", attributes or {})
    if parent is not None:
        parent.append(result)
    return result


def brush(value):
    if value == "none":
        return "{x:Null}"
    if value == "currentColor":
        value = "#52645C"
    return "{StaticResource Controller.Brush." + PALETTE[value] + "}"


def convert(source, fill="#52645C", include_pressed=False, stroke=None, stroke_width="1"):
    if source.get("class") == "pressed" and not include_pressed:
        return None
    tag = source.tag.split("}")[-1]
    fill = source.get("fill", fill)
    stroke = source.get("stroke", stroke)
    stroke_width = source.get("stroke-width", stroke_width)
    if tag == "g":
        result = element("DrawingGroup")
        if source.get("opacity"):
            result.set("Opacity", source.get("opacity"))
        for child in source:
            drawing = convert(child, fill, include_pressed, stroke, stroke_width)
            if drawing is not None:
                result.append(drawing)
    elif tag in ("path", "ellipse"):
        result = element("GeometryDrawing", {"Brush": brush(fill)})
        if tag == "path":
            # SVG's default is nonzero winding; WPF's default is even-odd.
            result.set("Geometry", "F1 " + source.attrib["d"])
        else:
            geometry = element("GeometryDrawing.Geometry", parent=result)
            element("EllipseGeometry", {
                "Center": f"{source.get('cx')},{source.get('cy')}",
                "RadiusX": source.get("rx"), "RadiusY": source.get("ry"),
            }, geometry)
        if stroke:
            pen = element("GeometryDrawing.Pen", parent=result)
            element("Pen", {"Brush": brush(stroke), "Thickness": stroke_width}, pen)
    else:
        return None
    if source.get("transform"):
        match = re.fullmatch(r"translate\(([-\d.]+)[,\s]+([-\d.]+)\)", source.get("transform"))
        if not match:
            raise ValueError(f"Unsupported SVG transform: {source.get('transform')}")
        wrapper = element("DrawingGroup")
        transform = element("DrawingGroup.Transform", parent=wrapper)
        element("TranslateTransform", {"X": match[1], "Y": match[2]}, transform)
        wrapper.append(result)
        result = wrapper
    return result


def generate():
    source = ET.parse(SVG).getroot()
    dictionary = element("ResourceDictionary")
    dictionary.append(ET.Comment(
        " SPDX-License-Identifier: CC0-1.0. Generated by scripts/sync-controller-artwork.py. "
        "Original artwork: Saikel Orado Liu. Vector adaptation and modifications: CC0-1.0. "
        "Source: https://github.com/univrsal/input-overlay/tree/master/presets/xbox-controller "
        "License: https://creativecommons.org/publicdomain/zero/1.0/ "
    ))
    for color, name in PALETTE.items():
        element("SolidColorBrush", {f"{{{XAML}}}Key": f"Controller.Brush.{name}", "Color": color}, dictionary)

    icon = element("GeometryGroup", {f"{{{XAML}}}Key": "Controller.Icon.Outline", "FillRule": "Nonzero"}, dictionary)
    icon_transform = element("GeometryGroup.Transform", parent=icon)
    element("ScaleTransform", {"ScaleX": str(22 / 2048), "ScaleY": str(22 / 2048)}, icon_transform)
    shell = next(group for group in source if group.get("id") == "shell-surface")
    for path in shell:
        geometry = element("PathGeometry", {"Figures": path.attrib["d"], "FillRule": "Nonzero"}, icon)
        if path.get("transform"):
            match = re.fullmatch(r"translate\(([-\d.]+)[,\s]+([-\d.]+)\)", path.get("transform"))
            if not match:
                raise ValueError("Unsupported icon outline transform")
            transform = element("PathGeometry.Transform", parent=geometry)
            element("TranslateTransform", {"X": match[1], "Y": match[2]}, transform)

    base = element("DrawingGroup", {f"{{{XAML}}}Key": "Controller.Base"}, dictionary)
    for group in source:
        name = group.get("id")
        if name is None:
            continue
        if name in ("left-stick", "right-stick"):
            cap = deepcopy(group)
            cap.attrib.pop("transform", None)
            drawing = convert(cap)
            drawing.set(f"{{{XAML}}}Key", f"Controller.{name}")
            dictionary.append(drawing)
        else:
            drawing = convert(group)
            if drawing is not None:
                base.append(drawing)
        pressed = next((child for child in group if child.get("class") == "pressed"), None)
        if pressed is None:
            continue
        wrapper = ET.Element(group.tag, dict(group.attrib))
        if name in ("left-stick", "right-stick"):
            wrapper.attrib.pop("transform", None)
        wrapper.append(deepcopy(pressed))
        drawing = convert(wrapper, include_pressed=True)
        drawing.set(f"{{{XAML}}}Key", f"Controller.Pressed.{name}")
        dictionary.append(drawing)

    ET.indent(dictionary, space="  ")
    target = ROOT / "app/Assets/ControllerArtwork.xaml"
    target.write_text(ET.tostring(dictionary, encoding="unicode") + "\n", encoding="utf-8")
    shutil.copyfile(SVG, ROOT / "app/Assets/controller.svg")
    license_source = ROOT / "docs/ux/controller-options/xbox-input-overlay.LICENSE.txt"
    legal = license_source.read_text(encoding="utf-8").split("Creative Commons Legal Code", 1)[1]
    license_target = ROOT / "app/ThirdParty/InputOverlay-Xbox/LICENSE.txt"
    license_target.parent.mkdir(parents=True, exist_ok=True)
    license_target.write_text(
        "SPDX-License-Identifier: CC0-1.0\n\n"
        "Applies to Assets/controller.svg and Assets/ControllerArtwork.xaml.\n"
        "Original Xbox Controller artwork: Saikel Orado Liu.\n"
        "Source: https://github.com/univrsal/input-overlay/tree/master/presets/xbox-controller\n"
        "Original CC0 declaration: https://github.com/univrsal/input-overlay/blob/master/presets/xbox-controller/README.md\n\n"
        "This SVG vector adaptation, its modifications and the derived WPF vector drawings\n"
        "are also dedicated to the public domain under CC0-1.0.\n"
        "License: https://creativecommons.org/publicdomain/zero/1.0/\n\n"
        "Creative Commons Legal Code" + legal,
        encoding="utf-8",
    )
    print(f"Generated {target.relative_to(ROOT)} from {SVG.relative_to(ROOT)}")


if __name__ == "__main__":
    generate()
